### ISSUE TITLE
[Bug] No Option to Set Consumption Size For Food/Drink Items

### ISSUE THREAD

**Issue by Manwe-fv** [Akkadius/spire#100]
As far as I can tell, Spire does not have any field to adjust food or drink consumption values, which are housed in field `casttime_`. I'm assuming this would be found in the spells section.

![image](https://user-images.githubusercontent.com/81694786/216835445-0155e29f-3fee-4e85-81c6-73893eb97295.png)

If you set `casttime_` to any value in the DB directly, then save the item in spire, reverts it back to 0. That obviously makes it impossible to adjust food stats, etc., without having to go back into the DB after the fact.

Here are the associated values: https://docs.eqemu.io/server/items/food-and-drink/

It would also be helpful if the item preview displayed the meal/drink message: "This is a miraculous meal!", etc.

**Comment by jcr4990** [comment]
I came here to post about this exact thing. Glad I checked before DMing or making another issue. I ended up having to make a thread in discord to ask how to set those values cause it wasn't super obvious and the docs (as far as I could tell) were missing the reference to the casttime_ field. I put in a PR to update that docs page to include it. Once I figured out what field it was I went through each tab of spire to double check and make sure I didn't miss it and it doesn't seem to be there. I can also confirm the casttime_ field is reset to 0 anytime the item is edited in Spire.

**Comment by Akkadius** [comment]
I'll fix it in the coming weeks during the bug bash

**Comment by Akkadius** [comment]
Also. The original item editor was to have "Simple views" for incredibly simple item types where you don't need to see an overwhelming amount of inputs, fields etc.

This would be great for things like tradeskill items, keys, bags, food etc.

This is still on my radar at some point
