### ISSUE TITLE
[Feature Request] Item editor pop-out, open to new tab, or option to enter a new item from current item edit window.

### ISSUE THREAD

**Issue by Turboquestserver** [Akkadius/spire#106]
If I'm doing multiple item edits it would be handy to be able to get to the next item without having to back out of the current item or reloading the item editor from the sidebar.  A pop-out that opens when you select an item to edit, leaving your search results / filters in tact on the main page would be useful, or even an input box on the editing page that allows you to move on to the next piece.  As of now, to my knowledge, you have to move backward to get to the next item.

**Comment by Akkadius** [comment]
In 3.0.0 release, these buttons become natural links where you can right click and open in a new tab if you'd like
