### ISSUE TITLE
Disabling pre-flight checks

### ISSUE THREAD

**Issue by Isaaru** [Akkadius/spire#117]
This doesn't seem to be working. Based on what the console displays it should be accomplished by adding: 

```
"server": {
  "disable_config_checks": true,
```

However it doesn't seem to actually stop the pre-flight checks from running.

**Comment by Akkadius** [comment]
I’ll take a look at this after a phone call

**Comment by Akkadius** [comment]
We took care of this while we were looking at it together with @valorith
