### ISSUE TITLE
[Bug] Task Editor - Not updating Task Title in list

### ISSUE THREAD

**Issue by tuday2** [Akkadius/spire#122]
When saving a change to the "title" of a task it does not update in the lefthand list, i have to click to reload the page to get the change to show up.

I circled the change and after clicking save it does not show up.

![image](https://github.com/Akkadius/spire/assets/27604078/41e394c1-c850-40ff-b6fd-4c90e696867c)

**Comment by tuday2** [comment]
Also, is there any way to change the ID that is created? I'd prefer to control what IDs my new tasks use.

**Comment by Akkadius** [comment]
Refresh task list title solved by release 3.2.2 https://github.com/Akkadius/spire/commit/40a89ea
