### ISSUE TITLE
Loot will not load with Spire launch - Windows

### ISSUE THREAD

**Issue by MortimerGreenwald** [Akkadius/spire#124]
Able to launch via the admin panel yet custom loot (added via DB) are not loading. Script loot works fine (default.pl).
When using Spire the default loots are working, as in if you're in Crushbone you'll see the regular loot entries.
Using the old script launch script all the customized loot is loading up fine.
Thx
Mort

**Comment by Akkadius** [comment]
This was solved by ensuring user was using shared memory
