### ISSUE TITLE
Export Form - Field Consistency

### ISSUE THREAD

**Issue by CoreAutomation-JD** [Akkadius/spire#125]
1. When viewing the form for database export, the default layout has compression enabled. When you uncheck the compression radio button all buttons get unchecked. 

2. If all radio buttons are unchecked, including individual tables for export, all tables will be exported regardless. This seems to be the same as having export all tables checked.

Suggestions:

I’d suggest unchecking compression does not affect the rest of the form. Perhaps also store a key in local storage that remembers my checked export preference, save a couple clicks every time I backup.

Also, I suggest having the export form throw a client toast/error if all tables is not checked and all other individual table radios are not checked.

**Comment by Akkadius** [comment]
This will be addressed in 3.3.4 as far as the issues with the form itself. The feature request I'd file separately
