### ISSUE TITLE
Spell Editor - Mutate View Require Focus, Not MouseOver

### ISSUE THREAD

**Issue by CoreAutomation-JD** [Akkadius/spire#127]
When viewing a spell, if I trigger a mouseover event on the spell id field, the sidebar will show a UI for picking a free spell id. However, if I trigger a mouseout event it does not dismiss. Focusing another field, such as spell name, will not dismiss it either. It seems there is a timer running that will dismiss it after some time.

I would suggest mutating the view to show the sidebar & sidebar contents based on focusing (clicking into) a field as opposed to hover/mouseover.

Alternatively, instead of a sidebar for spell ids, show a dropdown on field focus that populates with available spell ids.

**Comment by Akkadius** [comment]
Addressed in 3.3.4

The sub-editor has two tabs and is too much to overload a dropdown select for
