### ISSUE TITLE
Item Create - Refresh Forced On Navigation

### ISSUE THREAD

**Issue by CoreAutomation-JD** [Akkadius/spire#128]
When you create or update an item a refresh is triggered (seems on a 5 second timer). If you navigate (EG. using back button) to change your view the event is not canceled and will fire. 

Example: Create item, see a notification that a refresh will trigger, click back (in this case takes back to a search result where I cloned an item from), the resulting search result page will mutate back to the item detail view.

Suggested Resolution: Remove the refresh or trigger it immediately on response from the backend.

**Comment by Akkadius** [comment]
Addressed in 3.3.4
