### ISSUE TITLE
[Bug] MOTD Cannot Set from Portal

### ISSUE THREAD

**Issue by brickbuckett** [Akkadius/spire#161]
**Navigation**
http://0.0.0.0:3000/admin/configuration/motd

**Expected Results**
Setting the MOTD from the Spire portal should modify the MOTD in-game

**Actual Results**
Doesn't seem to do anything at all regardless of what you type in or how many times you click "save"

**Comment by Akkadius** [comment]
![image](https://github.com/Akkadius/spire/assets/3319450/b0ebc43d-f440-4ec2-be29-db0697896c64)

Will be fixed in next release
