### ISSUE TITLE
[Bug] "(44) Client Login" Logs Don't Output over Discord Webhook

### ISSUE THREAD

**Issue by brickbuckett** [Akkadius/spire#162]
"(44) Client Login" logs don't output to a discord webhook whether it's set to normal or detailed logging level.

**Expected Results**
Logs generated in login_######.log should be reflected in the Discord webook

**Actual Results**
Nothing gets posted to Discord at all

**Comment by Akkadius** [comment]
This is more of a EQEmu/Server issue - this is because the Loginserver does not ship Discord logs to UCS which is where messages are processed. Only zone has a function hook to ship to UCS
