### ISSUE TITLE
Unable to start browser interface

### ISSUE THREAD

**Issue by Sinjinx** [Akkadius/spire#169]
I'm quite addicted to Spire at this point, but a few updates back my locally installed application stopped initializing the browser. The app seems to start and I briefly see the window (cmd prompt window) before ending with no other result. The app still does seem to update itself and will stay active for that and my press of the enter key to stop Spire, but goes back to just ending after a quick cmd window after.

All was well up until this issue - it's been a bit over a week since it started.

**Comment by Akkadius** [comment]
I'm unable to reproduce this myself. Can you open up a `cmd.exe` window, cd to your server directory, run `spire.exe` manually and show me the output or error you are running into ?

**Comment by Sinjinx** [comment]
Sure, I'll do it now. Sorry for the delay :)

looks like this:

C:\eqemu>spire-windows-amd64.exe

C:\eqemu>

No error at all. It's like the browser should be opening and running spire, but it doesn't.

**Comment by Sinjinx** [comment]
And to be clear, there is no Spire cmd window, nor does the browser open. Both of these things worked normally until a week or two ago. Also, when there is an update it completes the update and I hit enter to quit before it returns to this behavior.

Hope that helps :)

**Comment by Akkadius** [comment]
This sounds like Windows getting in the way or preventing launch
