### ISSUE TITLE
Crash when offline

### ISSUE THREAD

**Issue by PetitRomeo** [Akkadius/spire#178]
Spire.exe crashes when you are offline because it can't access this github to see if there's updates. Is there a way I could disable those auto-updates?

**Comment by Akkadius** [comment]
Do you have a screenshot of this issue ?

**Comment by PetitRomeo** [comment]
![Capture d’écran 2024-05-17 021854](https://github.com/Akkadius/spire/assets/119537831/eead6936-3306-45e9-a7fe-4b575a5c436a)
![Capture d’écran 2024-05-17 021729](https://github.com/Akkadius/spire/assets/119537831/86224e21-7de6-456f-8216-67d977023d03)

**Comment by PetitRomeo** [comment]
The sentence "Appuyez sur une touche pour continuer..." is the french sentence Windows shows you for the "pause" command. It simply means "Press a key to continue..."

**Comment by Akkadius** [comment]
Thanks for that. I’ll get a patch out

**Comment by Akkadius** [comment]
This should hopefully be fixed in 4.1.0
