### ISSUE TITLE
[Quest API] Upper case characters in quest::UpdateSpawnTimer are not supported as shown in spire

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#22]
Upper case characters in this method (As shown on spire) cause it to not be recognized: http://spire.akkadius.com/quest-api-explorer?lang=perl&q=updatespawn&h=UpdateSpawnTimer

**Comment by Akkadius** [comment]
Fixed by https://github.com/EQEmu/Server/pull/1947/files
