### ISSUE TITLE
[Bug] Attempting to save a changed Goal ID results in the below error

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#34]
Error binding to entity [code=400, message=Unmarshal type error: expected=uint, got=string, field=task_activities.goalid, offset=623, internal=json: cannot unmarshal string into Go struct field TaskActivity.task_activities.goalid of type uint]

**Comment by Valorith** [comment]
Same for Goal Count

**Comment by Akkadius** [comment]
Yeah I'm going to need to make sure the forms are sending the right types up. Didn't quite get to that, thanks for making a note

**Comment by Akkadius** [comment]
Fixed in next push
