### ISSUE TITLE
[Task Editor: Bug] Intermittent issue displaying task activity fields after activity deletion.

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#42]
Sometimes when you delete an activity from a task, the activity fields below the activity do not appear for the last activity in the list.

Issue is not resolved by refreshing the browser.

![image](https://user-images.githubusercontent.com/76063792/163658630-18da1ae1-7ac1-434f-a738-de1aa2cab381.png)

**Comment by Akkadius** [comment]
I haven't been able to reproduce this one

**Comment by Valorith** [comment]
I had it happen once this morning...its somewhat rare...i usually just delete it and remake the activity and am fine. I can't reliably reproduce it either.

**Comment by Akkadius** [comment]
Have you been able to get a repro for this one ?

**Comment by Akkadius** [comment]
Resolved in latest
