### ISSUE TITLE
[Task Editor: Bug] Some Task activities cannot be re-sorted

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#45]
I have not been able to figure out the causal factor yet, but some work, some don't.

**Comment by Valorith** [comment]
I haven't been able to replicate the issue on any of the stock tasks, only on custom tasks that i made a few days ago...although i don't see a noticeable difference in the editor on the activities that won't budge.

**Comment by Valorith** [comment]
This one can be reordered
```
{
  "taskid": 42,
  "activityid": 9,
  "step": 6,
  "activitytype": 1,
  "target_name": "Korbuk Brimblade",
  "item_list": "",
  "skill_list": "-1",
  "spell_list": "0",
  "description_override": "Deliver 1 Vial of Blackfall Blood to Korbuk Brimblade",
  "goalid": 60304,
  "goalmethod": 0,
  "goalcount": 1,
  "delivertonpc": 110088,
  "zones": 110,
  "optional": 0
}
```

This one can not
```
{
  "taskid": 42,
  "activityid": 10,
  "step": 7,
  "activitytype": 2,
  "target_name": "Bristlebane the King of Thieves",
  "item_list": "",
  "skill_list": "-1",
  "spell_list": "0",
  "description_override": "",
  "goalid": 126373,
  "goalmethod": 0,
  "goalcount": 1,
  "delivertonpc": 0,
  "zones": 126,
  "optional": 0
}
```

**Comment by Valorith** [comment]
I recreated this task from scratch and all activities can be moved. There must just be something with custom tasks that were created before these recent updates that makes some activities unmovable. Closing this.

**Comment by Valorith** [comment]
I was able to replicate this on a newly created task and i think i have it isolated to when you exceed 10 activities (index 10+). It seems to be at this point that sorting gets borked.

Looking at the console...it appears maybe activity w/ index of 10 is showing as 1?
![image](https://user-images.githubusercontent.com/76063792/163683895-07853f75-db1d-4ac7-b05e-dbaaf6bb8fd6.png)

**Comment by Akkadius** [comment]
Weird javascript issue, resolved in branch
