### ISSUE TITLE
[Task Editor: Possible Optimization]

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#47]
Scenario:

You are editing tasks. 
You click into "Goal ID"-> The NPC Selector opens.
You start to move the mouse over to the NPC selector to make a selection, etc...BUT...there are several textboxes in between the Goal ID text box and the right side of the screen. 
If you mouse-over one of the other text boxes, the npc selector goes poof and you have to start over. 

Is there a way to add a hover delay of some sort before anything changes with the selector component?

**Comment by Akkadius** [comment]
The hover delay is currently 5000ms (5s)

```typescript
const MILLISECONDS_BEFORE_WINDOW_RESET = 5000;
```

Is that not enough ?

**Comment by Valorith** [comment]
Seems fine currently
