### ISSUE TITLE
[Task Editor: Bug] Activity Type 6 is using the Activity Target value for description instead of Item List

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#48]
Need to change Task activities with an Activity Type of 6 (Tradeskill) to use the Item List value in the activity description instead of the Activity Target value (current functionality).

![image](https://user-images.githubusercontent.com/76063792/163716419-c22e3f63-7996-4be3-902f-30fe62010401.png)

**Comment by Akkadius** [comment]
Deliver

![image](https://user-images.githubusercontent.com/3319450/168185639-c88554af-1576-4235-88a1-a7e8603ea304.png)

Loot

![image](https://user-images.githubusercontent.com/3319450/168185646-80091f51-d48c-454a-ac4f-6a07d4e32dbe.png)

Tradeskill

![image](https://user-images.githubusercontent.com/3319450/168185656-3d82f572-0a15-48cf-9cc0-87f559c1364b.png)

Fish

![image](https://user-images.githubusercontent.com/3319450/168185670-0c804834-f42b-467f-8d35-38f7deaad50f.png)

Forage

![image](https://user-images.githubusercontent.com/3319450/168185687-cf624450-6281-4a7d-b965-47d3878fe36a.png)

**Comment by Akkadius** [comment]
```
[x] Audit activity description formatting
	- https://github.com/Akkadius/spire/issues/48
	  - [x] Deliver
	  - [x] Kill
	  - [x] Loot
	  - [x] Speak With
	  - [x] Explore
	  - [x] Tradeskill
	  - [x] Fish
	  - [x] Forage
	  - [?] Use
	  - [?] Use
	  - [?] Touch
	  - [?] Give Cash
```
