### ISSUE TITLE
[Task Editor: Feature Request] Make Zone default value for Activity Type 6 (Tradeskill) be 0 (no zone)

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#49]

**Comment by Akkadius** [comment]
In what case is this present ?

**Comment by Valorith** [comment]
When you create a new task activity and set the Activity Type to 7 (Tradeskill), currently the default zone id is 21 (West Commons). More often than not, you dont care about the zone when creating a Tradeskill activity, and thus you usually will be deleting the default zone value. Setting the default zone to 0 (No Zone) for Activity Type 6 will remove this step.

![image](https://user-images.githubusercontent.com/76063792/167724810-da9445c9-7eda-4635-abef-95d327b1550e.png)

**Comment by Akkadius** [comment]
I think I'll have zone 0 out when activity type changes

**Comment by Valorith** [comment]
Makes sense to me

**Comment by Akkadius** [comment]
This will be in latest
