### ISSUE TITLE
[Task Editor: Optimization] When Item/NPC Selector search box gets focus, auto-highlight any existing text.

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#52]
When you open up the item and npc selector and send focus to the search box, auto-highlighting the default text would allow you to immediately start typing, as apposed to having to delete the default value first.

**Comment by Akkadius** [comment]
What do you mean "as apposed to having to delete the default value first"?

**Comment by Valorith** [comment]
When you open up the npc selector, the current npcid is shown in the search box and the search box is given focus. If you want to start searching for a new npc, you have to delete the pre-loaded npc-id before you can start typing your search. 

If you auto-highlight the pre-loaded npc-id when the npc selector is displayed, users can immediately start typing a search and it will override the pre-loaded npcid automatically.  This just removes a step (delete current npcid) if the user wants to search for a new npc.

![image](https://user-images.githubusercontent.com/76063792/167724095-eef44e82-67f3-424c-ba8e-734a1db81f10.png)

**Comment by Akkadius** [comment]
I think what you're asking is bringing the input focus to that field.

**Comment by Valorith** [comment]
> I think what you're asking is bringing the input focus to that field.

I think the box already gets focus....I was specifically suggesting that the text in that box be highlighted/selected. 

If you just give the box focus, then you have to delete the current value before you can start a new search.

If you highlight the text inside the search box by default, you can immediately start typing your search if desired and it will override the highlighted text.

Just an idea. A lot of these little efficiency improvement add up when making a bunch of lengthy tasks :P 

Not a big deal either way though :)

**Comment by Akkadius** [comment]
This will be in the next release
