### ISSUE TITLE
[Task Editor: Feature Request]

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#53]
When using the description editor component and editing activity level descriptions, provide the default activity description to the user for reference.

**Comment by Akkadius** [comment]
Can you elaborate on this one as well ?

**Comment by Valorith** [comment]
![image](https://user-images.githubusercontent.com/76063792/167723455-80e75501-e158-4d64-8547-3d2fe583f067.png)

**Comment by Akkadius** [comment]
Ahh, thought it was obvious enough to be able to go to your activities and see them listed. We really need to draw it in another place?

**Comment by Valorith** [comment]
Perhaps not. I just thought it might be handy to see what activity your writing a description for, if you are working on a really long task and you dont have the activity order all memorized. I have the memory of a gold fish most of the time :P

**Comment by Akkadius** [comment]
This will be in latest
