### ISSUE TITLE
[Task Editor: Feature Request] In the Description Selector, parse CRLF and replace with <br>

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#54]

**Comment by Akkadius** [comment]
Can you elaborate more on this?

**Comment by Valorith** [comment]
When adding a global description. If you put a new line in your description, automatically replace it with `<br>`

**Comment by Akkadius** [comment]
ahh yeah I see what you mean now. Had intended on doing that anyhow

**Comment by Akkadius** [comment]
This will be in latest
