### ISSUE TITLE
[Task Editor: Bug] Task Step as shown in the activities list and the Task Step textbox can get out of sync

### ISSUE THREAD

**Issue by Valorith** [Akkadius/spire#55]
Task Step as shown in the activities list and the Task Step textbox can get out of sync when deleting tasks and/or reordering tasks.

I will try to narrow this down more as I get time today.

**Comment by Akkadius** [comment]
Yeah I'll need more info on this one, especially a reproduce

**Comment by Valorith** [comment]
![image](https://user-images.githubusercontent.com/76063792/167722161-d5d31440-1e71-4307-91d1-44c16b1bdaca.png)

**Comment by Akkadius** [comment]
This is strange considering they are projections of the same data.

My guess is there is some sort of javascript error triggering on change of highlight

**Comment by Akkadius** [comment]
Resolved in latest
