### ISSUE TITLE
Spire - radiant_crystals Column is not in the table

### ISSUE THREAD

**Issue by MortimerGreenwald** [Akkadius/spire#62]
See Screenshot:
Error Updating.

Trust [Wayfarers Haven] — Today at 10:17 AM
Because Spire hasn't been updated for https://github.com/EQEmu/Server/pull/2317 I assume

![unknown](https://user-images.githubusercontent.com/110543605/182931517-6dbe7a9e-d4d1-4a26-bb0b-32dc51adbbf7.png)

**Comment by Akkadius** [comment]
Resolved by https://github.com/Akkadius/spire/commit/f0f9e714079efd6cb8336af62c9f3261c1b9cbd1
