### ISSUE TITLE
Using the + to add in another activity within a task, wipes out what was in the list prior

### ISSUE THREAD

**Issue by MortimerGreenwald** [Akkadius/spire#66]
Was testing today.. Started adding multiple activities.... i added 3 and populated them.. Then hit the + button, and it wiped out the 2 except for the first one with the default kill activity.

![image](https://user-images.githubusercontent.com/110543605/185947228-88a9a880-17c1-407f-8e9a-8a910efe04f3.png)

**Comment by Akkadius** [comment]
This should be addressed in the next major update
