### ISSUE TITLE
DB Strings (dbstr_us.txt) downloads a 0 KB file.

### ISSUE THREAD

**Issue by MortimerGreenwald** [Akkadius/spire#68]
nothing in the txt file... spells_us.txt works fine

**Comment by Valorith** [comment]
Working fine for me on hosted spire

**Comment by Akkadius** [comment]
Need to have db strings in the database table for it to download anything

**Comment by MortimerGreenwald** [comment]
Odd. I used Akk installer originally. Any guide to How to add the db strings?

**Comment by MortimerGreenwald** [comment]
I'm an idiot
