### ISSUE TITLE
[Bug] Can't save edited Bot Spell entry when using a number in String field "Bucket_Name or Bucket_Value"

### ISSUE THREAD

**Issue by Aeadoin** [Akkadius/spire#83]
Both Bucket_Name and Bucket_Value are strings values which should be able to accept a number value.

It's pretty common to use a number in the Table data_buckets.Value" Field, which is a text field, which bot_spells_entries.Bucket_Value uses to determine if a bot can use a spell. same with Bucket_name (but less likely to just be a number)

![image](https://user-images.githubusercontent.com/109764533/201704790-e01893ee-c986-4f2f-883d-be459fc7e7ac.png)

**Comment by Akkadius** [comment]
This should be fixed in 3.0.0
