### ISSUE TITLE
items show Combat Effects, including those with a value of 0

### ISSUE THREAD

**Issue by R-QualiPdf** [Akkadius/spire#90]
For quite a few releases now, all items show Combat Effects, including those with a value of 0.

**Comment by Akkadius** [comment]
Can you show an example screenshot

**Comment by R-QualiPdf** [comment]
![watersprinkler](https://user-images.githubusercontent.com/104461183/212069876-97073acb-3616-4e24-a98f-ccb8092f1758.jpg)

**Comment by R-QualiPdf** [comment]
![finesteellongsword](https://user-images.githubusercontent.com/104461183/212070260-f9dcb9e3-a818-4fb2-b3c5-07f132ca7b64.jpg)

Actully, Epic 1.0 are modified on my server and have an extra augmentation slot. Here is unmodified item.

**Comment by Akkadius** [comment]
![image](https://user-images.githubusercontent.com/3319450/212072667-6b6314c4-756c-4cf2-b2ff-0524551f2727.png)

Release is going up (2.5.5)
