### ISSUE TITLE
[Feature Request] Could Corruption be added to resist types?

### ISSUE THREAD

**Issue by Spoonface-CAN** [Akkadius/spire#92]
When editing spells and selecting the resist type, the list does not give a selection for slot 9, corruption.
If you get time, not a huge issue.
Thanks :)

![spire resist types](https://user-images.githubusercontent.com/66483953/213545236-2dbc1cee-e7f3-4c77-89a5-3de8a41ce356.png)

**Comment by Akkadius** [comment]
Will be addressed in release 3.0.0
