### ISSUE TITLE
Sometimes can't lookup items by name or ID

### ISSUE THREAD

**Issue by Aeadoin** [Akkadius/spire#99]
Some items I can't look up at all in Spire against the KMRA database, I know others have seen similar behavior for their own servers.

It gets stuck

![image](https://user-images.githubusercontent.com/109764533/216071234-5ca32404-968c-46fa-a907-6651bddf1d8b.png)

HAR upload:

[spire.akkadius.com_Archive [23-02-01 09-29-54].zip](https://github.com/Akkadius/spire/files/10558014/spire.akkadius.com_Archive.23-02-01.09-29-54.zip)

**Comment by Aeadoin** [comment]
I think this is related searching items that have the same name as another item, as it seems to only happen when there is another version of the item. but doesn't seem to effect Placeholders.

**Comment by Akkadius** [comment]
i'm not sure what a .har is
